name: Pre-update
description: Run the required steps before updating the ICS files.

runs:
  using: "composite"
  steps:
    - name: Merge updates from 'main'
      run: git fetch origin live:live && git checkout live -- docs/ics
      shell: bash
    - name: Setup node
      uses: actions/setup-node@v4
      with:
        node-version: 25
    - name: Install dependencies
      run: npm install
      shell: bash