name: Automatic update

on:
  schedule:
    - cron: "0 * * * *" # Every hour
  push:
    branches: ["main"]

concurrency:
  group: "update-calendar"
  cancel-in-progress: false

jobs:
  publish:
    runs-on: ubuntu-latest

    environment:
      name: github-pages
      url: "${{ steps.deployment.outputs.page_url }}"

    permissions:
      contents: write
      pages: write
      id-token: write

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4
        with:
          ref: 'main'
      - name: Prepare update
        id: prepare
        uses: ./.github/workflows/pre-update
      - name: Update FIH calendar
        if: ${{ success() || (!cancelled() && steps.checkout.outcome == 'success' && steps.prepare.outcome == 'success') }}
        continue-on-error: true
        run: npm run fetch fih
      - name: Update EHL calendar
        if: ${{ success() || (!cancelled() && steps.checkout.outcome == 'success' && steps.prepare.outcome == 'success') }}
        run: npm run fetch ehl
      - name: Update KNHB calendar
        if: ${{ success() || (!cancelled() && steps.checkout.outcome == 'success' && steps.prepare.outcome == 'success') }}
        run: npm run fetch knhb
      - name: Update WMH calendar
        if: ${{ success() || (!cancelled() && steps.checkout.outcome == 'success' && steps.prepare.outcome == 'success') }}
        run: npm run fetch wmh
      - name: Update EH calendar
        if: ${{ success() || (!cancelled() && steps.checkout.outcome == 'success' && steps.prepare.outcome == 'success') }}
        run: npm run fetch eh        
      - name: Finalize update
        if: ${{ success() || (!cancelled() && steps.checkout.outcome == 'success' && steps.prepare.outcome == 'success') }}
        uses: ./.github/workflows/post-update
      - name: Notify in case of failure
        if: failure()
        uses: dothq/actions-status-discord@v1.0.4
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          nofail: false